//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oformlenie_biletov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id_payment { get; set; }
        public long Card_number { get; set; }
        public System.DateTime Time_payment { get; set; }
    
        public virtual Ticket_cost Ticket_cost { get; set; }
    }
}
