//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oformlenie_biletov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_cost
    {
        public int Id_ticket_cost { get; set; }
        public int Cost { get; set; }
        public string Status { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
