//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oformlenie_biletov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id_ticket { get; set; }
        public long Ticket_number { get; set; }
        public string Carrige_type { get; set; }
        public int Carrige_number { get; set; }
        public int Place_number { get; set; }
        public int PassengerId_passenger { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual Ticket_cost Ticket_cost { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
